/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // Star Halal design system (from Stitch export) - warm heritage palette,
        // not "tech blue". Keep these names in sync with DESIGN.md if it's ever regenerated.
        surface: "#FDF9F3",
        "surface-dim": "#DCD2C4",
        "surface-bright": "#FDF9F3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#F7F1E8",
        "surface-container": "#F1EAE0",
        "surface-container-high": "#EAE2D6",
        "surface-container-highest": "#E4DBCE",
        "on-surface": "#1A1A1A",
        "on-surface-variant": "#5A4A3A",
        "inverse-surface": "#2A2724",
        "inverse-on-surface": "#F7F1E8",
        outline: "#8A7A63",
        "outline-variant": "#E0D3BC",
        "surface-tint": "#B4141F",
        primary: "#B4141F",
        "on-primary": "#ffffff",
        "primary-container": "#B4141F",
        "on-primary-container": "#F2A9A0",
        "inverse-primary": "#F2A9A0",
        secondary: "#8C0F18",
        "on-secondary": "#ffffff",
        "secondary-container": "#d0e4d8",
        "on-secondary-container": "#6E0B12",
        tertiary: "#00325f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#004985",
        "on-tertiary-container": "#88b9fd",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#FBE3E0",
        "primary-fixed-dim": "#F2A9A0",
        "on-primary-fixed": "#6E0B12",
        "on-primary-fixed-variant": "#8C0F18",
        "secondary-fixed": "#d3e7db",
        "secondary-fixed-dim": "#b7cbbf",
        "on-secondary-fixed": "#0e1f17",
        "on-secondary-fixed-variant": "#2F6B4F",
        "tertiary-fixed": "#d3e3ff",
        "tertiary-fixed-dim": "#a3c9ff",
        "on-tertiary-fixed": "#001c39",
        "on-tertiary-fixed-variant": "#004883",
        background: "#FDF9F3",
        "on-background": "#1A1A1A",
        "surface-variant": "#E4DBCE",
        // Meat Vanta gold - highlights and premium touches
        accent: "#C8952B",
        "accent-soft": "#F3E4C4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "sidebar-width": "260px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-bold": ["Hanken Grotesk"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
